# Generated by Django 5.2.3 on 2025-11-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('depression', 'Overcame Depression'), ('relationship', 'Fixed My Relationship'), ('study', 'Study Success Journey'), ('addiction', 'Quit Addiction'), ('career', 'Career Failures → Success'), ('friendship', 'Friendship Breakups'), ('motivation', 'Motivation'), ('growth', 'Personal Growth')], max_length=30)),
                ('anonymous', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('reads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
